# Generated by Django 5.1.15 on 2026-05-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_profile_age_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
