# Generated by Django 5.1.15 on 2026-03-22 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articles_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Ogłoszenie', 'verbose_name_plural': 'Ogłoszenia'},
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('elektronika', 'Elektronika'), ('dom', 'Dom i Ogród'), ('moda', 'Moda'), ('motoryzacja', 'Motoryzacja'), ('inne', 'Inne')], default='inne', max_length=50, verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='articles',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(blank=True, verbose_name='Pełny opis przedmiotu'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='excerpt',
            field=models.CharField(max_length=250, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data publikacji'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tytuł ogłoszenia'),
        ),
    ]
