# Generated by Django 5.1.15 on 2026-03-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_options_articles_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ogloszenia/', verbose_name='Zdjęcie przedmiotu'),
        ),
    ]
