# Generated by Django 5.1.15 on 2026-03-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
