# Generated by Django 5.1.15 on 2026-03-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_articles_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='views',
        ),
    ]
