# Generated by Django 5.2.6 on 2026-03-26 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_articles_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ulubione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dodania', models.DateTimeField()),
                ('ogloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulubione', to='news.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulubione', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ogloszenie')},
            },
        ),
    ]
