# Generated by Django 5.2.6 on 2026-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_ulubione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulubione',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
