# Generated by Django 5.1.15 on 2026-04-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_ulubione_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Zdjęcie'),
        ),
    ]
